# _config.yml
title: "Sukanta Mondal"
description: "Academic portfolio and professional profile"
baseurl: "" # leave empty for root site
url: "https://<your-github-username>.github.io" # replace with your GitHub Pages URL

# Theme
theme: minimal-mistakes-jekyll

# Author information
author:
  name: "Sukanta Mondal"
  avatar: "/assets/images/profile.jpg" # optional, add your image in /assets/images/
  bio: "Assistant Professor in Chemistry at Assam University, specializing in theoretical and computational chemistry."
  location: "Silchar, Assam, India"
  email: "sukanta.mail13@gmail.com"
  links:
    - label: "Website"
      icon: "fas fa-globe"
      url: "https://sites.google.com/site/sukantamondalaus/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0003-1918-8202"
    - label: "Scopus"
      icon: "fas fa-book"
      url: "https://www.scopus.com/authid/detail.uri?authorId=57209528324"

# Social Links
social:
  type: "Person"
  name: "Sukanta Mondal"
  links:
    - "mailto:sukanta.mail13@gmail.com"
    - "https://sites.google.com/site/sukantamondalaus/"
    - "https://orcid.org/0000-0003-1918-8202"
    - "https://www.scopus.com/authid/detail.uri?authorId=57209528324"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Navigation menu
nav:
  - title: "Home"
    url: /
  - title: "Experience"
    url: /Experience/
  - title: "Education"
    url: /Education/
  - title: "Courses"
    url: /Courses/
  - title: "Publications"
    url: /Publications/
  - title: "Book Chapters"
    url: /Book-Chapters/
  - title: "Projects"
    url: /Projects/
  - title: "Reviewer & Editor"
    url: /Reviewer-Editor/
  - title: "Awards"
    url: /Awards/
  - title: "Conferences"
    url: /Conferences/
  - title: "Service"
    url: /Service/
  - title: "Miscellaneous"
    url: /Miscellaneous/

# Pagination (optional)
paginate: 10
paginate_path: "/page:num/"
