title: "Chemistry Through Computation"
description: "Academic portfolio and professional profile — Sukanta Mondal"

# Your site URL
baseurl: ""  
url: "https://smctc.github.io"

# Navigation menu links
navigation:
  - title: "Home"
    url: "/"
  - title: "Experience"
    url: "/Experience"
  - title: "Education"
    url: "/Education"
  - title: "Courses"
    url: "/Courses"
  - title: "Publications"
    url: "/Publications"
  - title: "Book Chapters"
    url: "/Book-Chapters"
  - title: "Projects"
    url: "/Projects"
  - title: "Reviewer & Editor"
    url: "/Reviewer-Editor"
  - title: "Awards"
    url: "/Awards"
  - title: "Conferences"
    url: "/Conferences"
  - title: "Service"
    url: "/Service"
  - title: "Miscellaneous"
    url: "/Miscellaneous"
