title: smctc
description: Academic portfolio and professional profile — Sukanta Mondal
baseurl: "" 
url: "https://smctc.github.io"

theme: jekyll-theme-minimal
- title: CBP-AI-IITRPR-C6 Assignments Portfolio
    url: /CBP-AI-IITRPR-C6-Assignments-Portfolio_SM/
