title: "Sukanta Mondal"
description: "Academic portfolio and professional profile"
baseurl: "" 
url: "https://<your-github-username>.github.io" # replace with your GitHub Pages URL

theme: minimal-mistakes-jekyll

# Navigation menu (appears at the top of every page)
header_pages:
  - index.md
  - Experience.md
  - Education.md
  - Courses.md
  - Publications.md
  - Book-Chapters.md
  - Projects.md
  - Reviewer-Editor.md
  - Awards.md
  - Conferences.md
  - Service.md
  - Miscellaneous.md

author:
  name: "Sukanta Mondal"
  email: "sukanta.mail13@gmail.com"
  links:
    - label: "Website"
      icon: "fas fa-globe"
      url: "https://sites.google.com/site/sukantamondalaus/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0003-1918-8202"
    - label: "Scopus"
      icon: "fas fa-book"
      url: "https://www.scopus.com/authid/detail.uri?authorId=57209528324"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Disable credits/footer clutter
footer:
  links: []
